// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtCSpb67SfvcDErxcY9tCcbzJRXKgFM4M',
    appId: '1:247444497634:web:335834ecd2068efce26abb',
    messagingSenderId: '247444497634',
    projectId: 'together-38380',
    authDomain: 'together-38380.firebaseapp.com',
    storageBucket: 'together-38380.appspot.com',
    measurementId: 'G-NT97XLBQSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGtN6gWtxvZeCa5QSPFHPdGZGI3MthUEc',
    appId: '1:247444497634:android:9e467d320a99ee30e26abb',
    messagingSenderId: '247444497634',
    projectId: 'together-38380',
    storageBucket: 'together-38380.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDenXCCdq0AVkQc2umH19A4yiIlU4zrl1E',
    appId: '1:247444497634:ios:6087eb48e828921ae26abb',
    messagingSenderId: '247444497634',
    projectId: 'together-38380',
    storageBucket: 'together-38380.appspot.com',
    iosBundleId: 'com.example.together',
  );
}
